# -*- coding: utf-8 -*-
"""10-MAʼLUMOTLARGA-ISHLOV-BERISH-10.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RoZTwVGTOKshSJFc4ZevYbuHh5g6yj2h

![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**
#10.5. Fayldan oʻqish va unga yozish. HDF5
**Bu vazifalarni bajargach, CSV, Excel va HDF5 formatlarida fayllarni oʻqish hamda saqlash, yaʼni data processing (ma’lumotlarga ishlov berish) koʻnikmasini oʻzlashtirasiz.**

#1-topshiriq


1.    Quyidagi link orqali maʼlumotlarni Pandas dataframeʼiga yuklab oling.
    
  *   https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv



2.   Yuklab olingan maʼlumotlarni `aqi.csv` fayliga saqlang.

3. Saqlab olingan `aqi.csv` faylining oxirgi 5 ta qatorini oʻqing.

Eslatma: fayl nomini `aqi.csv` deb saqlaganimizning sababi AQI – Air Quality Index, yaʼni havo sifati indeksi deganidir. Bizning maʼlumotlarimizda davlatlarning havo sifati haqidagi maʼlumotlar saqlangan!
"""

import pandas as pd
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv"
#javobni shu yerda yozing.
df=pd.read_csv(url)
df.to_csv("aqi.csv")
df.tail()

"""#2-topshiriq
1. Saqlab olingan `aqi.csv` faylidagi maʼlumotlarning faqat 2024-yilga tegishlisini excel faylga `aqi_2024.xlsx` koʻrinishida saqlab oling.
2. Saqlab olingan `aqi_2024.xlsx` faylidan Oʻzbekistonga tegishli maʼlumotni (qatorlarni) oʻqing.
"""

#javobni shu yerda yozing.
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv")

df['Date'] = pd.to_datetime(df['Date'])

df_2024 = df[df['Date'].dt.year == 2024]

df_2024.to_excel("aqi_2024.xlsx", index=False)

df_excel = pd.read_excel("aqi_2024.xlsx")
df_excel[df_excel['Country'] == 'Uzbekistan']

"""#3-topshiriq
1. `aqi.csv` faylidagi maʼlumotlarni oʻrganib chiqsangiz, bu faylda 2022–2025-yillar oraligʻidagi havo sifati haqidagi maʼlumotlarni koʻrishingiz mumkin. Hozir sizga vazifa:
  * `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllariga `aqi.csv` faylidagi maʼlumotlarning mos davrlarini saqlang. Misol uchun, `aqi_2022` fayli 2022-yildagi havo sifati haqidagi maʼlumotlarni oʻzida saqlaydi.
  
"""

#javobni shu yerda yozing.
import pandas as pd

df = pd.read_csv("aqi.csv")
df['Date'] = pd.to_datetime(df['Date'])

df2=df[df['Date'].dt.year == 2022].to_csv("aqi_2022.csv", index=False)
df[df['Date'].dt.year == 2023].to_csv("aqi_2023.csv", index=False)
df[df['Date'].dt.year == 2024].to_csv("aqi_2024.csv", index=False)
df[df['Date'].dt.year == 2025].to_csv("aqi_2025.csv", index=False)

df2=pd.read_csv("aqi_2022.csv")
df2.head()

"""#4-topshiriq
1. Saqlab olingan `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllarini HDF5 formatida saqlang. Fayl nomini `aqi.h5` deb nomlang. Kalit (key) sifatida fayllarning yillarini bering. Misol uchun, key=2025.
"""

#javobni shu yerda yozing.
import pandas as pd

with pd.HDFStore("aqi.h5") as store:
    store.put("2022", pd.read_csv("aqi_2022.csv"), format="table")
    store.put("2023", pd.read_csv("aqi_2023.csv"), format="table")
    store.put("2024", pd.read_csv("aqi_2024.csv"), format="table")
    store.put("2025", pd.read_csv("aqi_2025.csv"), format="table")

"""#5-topshiriq
1. `aqi.h5` faylidan maʼlumotlarni oʻqing va 2025-yilga tegishli maʼlumotlarni yangi dataframeʼga saqlang.
2. `aqi.h5` faylida 2025-yilning qaysi oylari uchun maʼlumotlar bor? Shu oylar roʻyxatini ekranga chiqaring!
"""

#javobni shu yerda yozing.
import pandas as pd

df_2025 = pd.read_hdf("aqi.h5", key="2025")

df_2025['Date'] = pd.to_datetime(df_2025['Date'])

df_2025['Date'].dt.month.unique()

