# -*- coding: utf-8 -*-
"""Copy of 10-MAʼLUMOTLARGA-ISHLOV-BERISH-10.25-YAKUNIY-AMALIY-VAZIFA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BW3Ugk0aYS3rG9SOFRKfy8RVMzLOiYhW

![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**

#**10.25. Modul boʻyicha yakuniy amaliy vazifa**

**Amaliyotni bajargach, fayllar bilan ishlash, API va veb sahifalardan ma’lumot olish, SQL soʻrovlarini yozish va ma’lumotlar omboriga ma’lumot saqlash koʻnikmalariga ega boʻlasiz.**

#**Fayldan oʻqish va yozish**

#**1) CSV fayldan maʼlumotlarni o‘qish**
* https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv havolasidagi maʼlumotlarni `df` oʻzgaruvchisiga saqlang!
* `df` dan tasodifiy 10 ta qatorni ekranga chiqaring!
"""

#javobni shu yerda yozing.
import pandas as pd

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv"
df = pd.read_csv(url)
df.sample(10)

"""#**2) CSV fayliga yozish**
* Quyidagi maʼlumotlardan dataframe yarating va uni `people_data.csv` fayliga saqlang.
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```
* Quyidagi maʼlumotlardan yana bir dataframe yarating va uni `people_data_2.csv` fayliga saqlang.
```
{
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}
```
"""

#javobni shu yerda yozing.
data1 = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
df1 = pd.DataFrame(data1)
df1.to_csv("people_data.csv", index=False)

data2 = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}
df2 = pd.DataFrame(data2)
df2.to_csv("people_data_2.csv", index=False)

"""#**3) HDF5 formati bilan ishlash**
* Yuqorida yaratgan dataframeʼlaringizni `people.h5` faylida saqlang.
* `people.h5` faylidagi barcha jadvallarni oʻqing!
"""

#javobni shu yerda yozing.
df1.to_hdf("people.h5", key="people1", mode="w")
df2.to_hdf("people.h5", key="people2")

pd.read_hdf("people.h5", key="people1")
pd.read_hdf("people.h5", key="people2")

"""#**4) JSON fayllar bilan ishlash**
1. Quyidagi maʼlumotlarni dataframe koʻrinishida oʻqing va uni `data.json` fayliga yozing!
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```

"""

#javobni shu yerda yozing.
df_json = pd.DataFrame(data1)
df_json.to_json("data.json", orient="records", indent=2)

"""#**5) APIʼlar bilan ishlash**
1. Quyida berilgan API 17 mingdan ortiq kriptovalyutalarning dollarga nisbatan narxi haqidagi maʼlumotlarni saqlaydi. Siz esa endi:
  * API orqali barcha maʼlumotlarni yigʻib oling;
  * ularni dataframe koʻrinishida saqlang;
  * maʼlumotlar boshidan 5 ta qatorni ekranga chiqaring;
  * maʼlumotlar ichidan `bitcoin` ni izlab toping!
"""

import requests
import pandas as pd

coins_url = "https://api.coingecko.com/api/v3/coins/list"
response = requests.get(coins_url)
coins = response.json()

# Check if the API returned an error status (e.g., rate limit)
if isinstance(coins, dict) and "status" in coins and "error_code" in coins["status"]:
    print(f"API Error: {coins['status']['error_message']}")
elif isinstance(coins, list):
    coins_df = pd.DataFrame(coins)
    print("First 5 rows of cryptocurrency data:")
    display(coins_df.head())

    print("\nSearching for 'bitcoin':")
    bitcoin_coin = coins_df[coins_df["id"] == "bitcoin"]
    display(bitcoin_coin)
else:
    print("Unexpected API response format.")
    print(coins)

"""#**6) APIʼlar bilan ishlash**
1. Yuqorida berilgan kriptovalyuta maʼlumotlaridan `id` ustunini roʻyxat koʻrinishida saqlang va bu roʻyxatga `coin_ids` deb nom bering.
2. https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies=usd havolasi orqali kriptovalyutalarning `usd` ga nisbatini oling (birinchi 100 ta maʼlumotni olish yetarli).
3. 2-shartda berilgan link orqali olingan maʼlumotlarni dataframe koʻrinishida saqlang. Bunda uning indeksi va `usd` ustuni boʻlsin. `index` -> kriptovalyutalar nomi, `usd` -> narxi

#**💡Ishora:** linkdagi `{coin_ids}` oʻzgaruvchi sifatida yozilgan. Siz ham 1-shartda saqlagan `coin_ids` oʻzgaruvchingizni shu qismda yozib keting!

"""

import requests
import pandas as pd

# Use coins_df from the previous step which was successfully populated
coin_ids = coins_df['id'].head(100).tolist()

ids_str = ",".join(coin_ids)

price_url = f"https://api.coingecko.com/api/v3/simple/price?ids={ids_str}&vs_currencies=usd"
prices = requests.get(price_url).json()

# Check if the API returned an error status (e.g., rate limit)
if isinstance(prices, dict) and "status" in prices and "error_code" in prices["status"]:
    print(f"API Error: {prices['status']['error_message']}")
elif isinstance(prices, dict):
    df = pd.DataFrame.from_dict(prices, orient="index")
    print("Cryptocurrency prices in USD (first 5 rows):")
    display(df.head())
else:
    print("Unexpected API response format for prices.")
    print(prices)

"""#**7) Veb sahifadan oʻqish**
1. Pandas yordamida veb sahifadagi jadvalni yuklab oling.
2. Ma’lumotlarni dataframe ko‘rinishida chiqaring.
3. Agar sahifada bir nechta jadval bo‘lsa, eng muhimini tanlang.
4. Ma’lumotni tozalang (bo‘sh qatorlarni olib tashlang, kerakli ustunlarni tanlang).
5. Natijani CSV faylga saqlang.

***Eslatma: manba sifatida oʻzingiz istagan veb sahifani tanlang. Bu vazifada mustaqil izlanishni oʻrganasiz!***
"""

#javobni shu yerda yozing.
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)"

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                         "(KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"}

response = requests.get(url, headers=headers)
response.raise_for_status()

tables = pd.read_html(response.text)
web_df = tables[0]

web_df = web_df.dropna()
web_df.to_csv("population.csv", index=False)

web_df.head(10)

"""# **Maʼlumotlar ombori bilan ishlash**

#**8) Maʼlumotlar omborini yuklash va ulanish**
1. https://github.com/alishermutalov/praktikum-datasets/blob/praktikum/chinook.db havolasi orqali maʼlumotlar omborini yuklab oling.
2. Yuklab olingan maʼlumotlar omboriga sqlite3 moduli yordamida **ulaning**.
"""

!wget https://github.com/alishermutalov/praktikum-datasets/raw/praktikum/chinook.db -O chinook.db

#javobni shu yerda yozing.
import sqlite3

conn = sqlite3.connect("chinook.db")

"""#**9) Maʼlumotlar omboriga soʻrov yuborish**
1. Jadvallar roʻyxatini koʻring. Ularning ichida `albums` jadvali boʻlsa, shu jadvaldagi barcha maʼlumotlarni (qatorlarni) ekranga chiqaring.
2. Qatorlar soni nechta ekanini aniqlab, uni ham ekranga chiqaring.
3.`albums` jadvalining ustunlari haqidagi maʼlumotlarni ekranga chiqaring.

"""

#javobni shu yerda yozing.
import sqlite3
import pandas as pd

conn = sqlite3.connect("chinook.db")
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print(tables)

"""#**10) SQL to DataFrame**
1. `albums` jadvalini `pandas.DataFrame` ga oʻtkazing!
"""

albums_df = pd.read_sql("SELECT * FROM albums", conn)
print(albums_df.head())

"""#**11)**  `chinook.db` maʼlumotlar omboridan `tracks` jadvalining birinchi 10 ta qatorini ekranga chiqaring

#💡Ishora: LIMIT
"""

#javobni shu yerda yozing.
tracks_df = pd.read_sql("SELECT * FROM tracks LIMIT 10", conn)
print(tracks_df.head())

"""#**12)**`tracks` jadvalidan faqat `Name`, `Composer` ustunlarini tanlab oling!"""

#javobni shu yerda yozing.
tracks_select_df = pd.read_sql("SELECT Name, Composer FROM tracks", conn)
print(tracks_select_df.head())

"""#**13) ORDER BY , DISTINCT**
* `tracks` jadvalidagi takrorlanmaydigan `GenreId` qiymatlarini oling.
* `tracks` jadvalidagi treklarni `Milliseconds` ustuni bo‘yicha kamayish tartibida saralang.

#💡Ishora: ORDER BY , DISTINCT
"""

#javobni shu yerda yozing.
genre_ids_df = pd.read_sql("SELECT DISTINCT GenreId FROM tracks", conn)
print(genre_ids_df)


tracks_ordered_df = pd.read_sql("SELECT * FROM tracks ORDER BY Milliseconds DESC", conn)
print(tracks_ordered_df.head())

"""#**14) Filtering**
 * `invoices` jadvalidan `Total` summasi 10 dan katta bo‘lgan maʼlumotlarni tanlang.

# 💡Ishora: WHERE
"""

#javobni shu yerda yozing.
invoices_filtered_df = pd.read_sql("SELECT * FROM invoices WHERE Total > 10", conn)
print(invoices_filtered_df.head())

"""#**15) CREATE and INSERT**
* `chinook.db` maʼlumotlar omboriga `users` jadvali yarating. Jadval maydonlari (ustunlar):
  * `id`
  * `name`
  * `birth_date`
* Yaratilgan `users` jadvaliga quyidagi maʼlumotlarni qoʻshing:

    * ```
    [
    ('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22),
    ('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31),
    ('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23),
    ('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21)
]
 ```

#💡Ishora: CREATE TABLE, INSERT

"""

#javobni shu yerda yozing.
cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    birth_date INTEGER
)
""")
users_data = [
    ('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22),
    ('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31),
    ('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23),
    ('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21)
]
cursor.executemany("INSERT INTO users (name, birth_date) VALUES (?, ?)", users_data)
conn.commit()

"""#**16) UPDATE and DELETE**
* `users` jadvalidagi Alice ismli foydalanuvchining yoshini yangilang.
* `users` jadvalidan Alice ismli foydalanuvchini o‘chiring.
"""

#javobni shu yerda yozing.
cursor.execute("UPDATE users SET birth_date = 26 WHERE name = 'Alice'")
cursor.execute("DELETE FROM users WHERE name = 'Alice'")
conn.commit()

"""#**17) f-string yordamida SQL komandalarini yozish**
* `customers` jadvalidan `FirstName` va `LastName` bo‘yicha qidiruv qiladigan f-string yozing.
"""

#javobni shu yerda yozing.
first_name = "John"
last_name = "Doe"
query = f"SELECT * FROM customers WHERE FirstName='{first_name}' AND LastName='{last_name}'"
print(query)

"""#**18)  AND and OR operators**

* `invoices` jadvalidan `BillingCountry` Germaniya yoki Fransiya boʻlgan va `Total` summasi 5 dan katta bo‘lgan kerakli qatorlarni tanlang.

#💡Ishora: AND, OR
"""

#javobni shu yerda yozing.
invoices_filtered_18 = pd.read_sql("""
SELECT * FROM invoices
WHERE (BillingCountry='Germany' OR BillingCountry='France') AND Total > 5
""", conn)
print(invoices_filtered_18.head())

"""#**19) BETWEEN and LIKE**

* `invoices` jadvalidan `Total` summasi 5 dan 15 gacha bo‘lgan qatorlarni tanlang.
* `customers` jadvalidan ismi `A` harfi bilan boshlanadigan foydalanuvchilarni tanlang.
"""

invoices_filtered_19 = pd.read_sql("""
SELECT * FROM invoices
WHERE Total BETWEEN 5 AND 15
""", conn)
print("Invoices with Total between 5 and 15:")
print(invoices_filtered_19.head())

customers_filtered_19 = pd.read_sql("""
SELECT * FROM customers
WHERE FirstName LIKE 'A%'
""", conn)
print("\nCustomers with FirstName starting with 'A':")
print(customers_filtered_19.head())

"""#**20) DataFrame to SQL**
* Quyidagi maʼlumotlardan dataframe yarating.
  ```
  sales_data = {
    "sale_id": list(range(1, 21)),  # 1 dan 20 gacha boʻlgan unikal IDʼlar
    "product_name": [
        "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
        "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
        "Speaker", "Game Console", "TV", "Router", "Power Bank",
        "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
    ],
    "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
    "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
              150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
    "sale_date": [
        "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
        "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
        "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
        "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
    ]
}
```
*Yuqoridagi maʼlumotlar asosida yaratgan dataframeʼingizdan SQL jadvali tuzing va uni `sales` deb nomlang.
"""

#javobni shu yerda yozing.
sales_data = {
  "sale_id": list(range(1, 21)),
  "product_name": [
      "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
      "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
      "Speaker", "Game Console", "TV", "Router", "Power Bank",
      "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
  ],
  "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
  "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
            150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
  "sale_date": [
      "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
      "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
      "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
      "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
  ]
}
sales_df = pd.DataFrame(sales_data)
conn.execute("DROP TABLE IF EXISTS sales")
sales_df.to_sql("sales", conn, index=False)
print("Sales jadvali yaratildi va ma'lumotlar saqlandi.")

